### ISSUE TITLE
New logo / icon

### ISSUE THREAD

**Issue by mansya** [TimOliver/TONavigationBar#4]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by TimOliver** [comment]
Hi there @mansya! 

Hahah thank you so much for the kind offer! This library is incredibly small though, and given recent iOS events, it's even become slightly broken. :( I don't think it's really worthy of a dedicated icon at the moment.

When it does, I'll let you know. Thanks again! :)
